### ISSUE TITLE
A small Rust application - little improvement

### ISSUE THREAD

**Issue by edomoli** [rust-lang/www.rust-lang.org#1088]
### Summary
I'd like to slightly change the code of section "A small Rust application", to be a bit more readable and flexible to user's changes.

> fn main() {
>    let stdout = stdout();
>    let message = String::from("Hello fellow Rustaceans!");
>    let width = message.len();
>
>    let mut writer = BufWriter::new(stdout.lock());
>    say(message.as_bytes(), width, &mut writer).unwrap();
>}

### Motivation
The new users, with this modification, can change the string said by Ferris the Crab easily, without changing the width accordingly (because it's dynamically calculated at runtime).

### Drawbacks
I don't have any drawbacks in mind.

### Rationale and alternatives
It is really a little modification, but in my opinion, it's useful to new users.
The alternative is to keep the code as it is now.

### Maintenance
Same design and maintainer.

### Unresolved Questions
N/A

**Comment by XAMPPRocky** [comment]
Thank you for your issue! If you'd like to make a PR changing the example code it is more than welcome!

**Comment by edoardo-molinatti** [comment]
You're welcome.
I made a local commit, on  a local branch that I called "get-started", but I'm unable to push, therefore I won't be able to open a Pull Request.
You could grant me the write access to the repository, so that I'll be able to push my commit on my branch. Or please tell me if you have another process in place, thank you in any case.

I also made a _patch_ that you should be able to _apply_ to your working copy and make the commit + push yourself, you can find it as an attachment (it's _zipped_ because otherwise I couldn't attach it to this post).

[patch#1088.zip](https://github.com/rust-lang/www.rust-lang.org/files/4548588/patch.1088.zip)

**Comment by XAMPPRocky** [comment]
@edoardo-molinatti I believe on github you first have to first fork the repo under your account and push to your fork to be able to open a pull request.
