### ISSUE TITLE
Add French Language

### ISSUE THREAD

**Issue by PTrottier** [rust-lang/www.rust-lang.org#1090]
### Page(s) Affected

Every page.

### What needs to be fixed?

Add the option for the French language to the language menu dropdown. I noticed that the translation already exists in the [codebase](https://github.com/rust-lang/www.rust-lang.org/tree/master/locales/fr), so it would be nice to make it accessible.

### Suggested Improvement

I'd be happy to tackle this.

**Comment by XAMPPRocky** [comment]
Thank you for your interest! If you'd like help contribute to the french localisation of the Rust website you can sign up for [Pontoon](https://pontoon.rust-lang.org/) to help contribute. Our french localisation team hangs out on Zulip (linked below), so you can reach out to them about how to help there.

https://rust-lang.zulipchat.com/#narrow/stream/226175-t-community.2Fl10n.2Ffr

**Comment by PTrottier** [comment]
I think this was prematurely closed, Pontoon already has the translation, the website is missing the option in the dropdown.

**Comment by XAMPPRocky** [comment]
Yes sorry, I should have explained that it is deliberate that it is currently not on the website. We generally only show languages that are have a high coverage and the localisation team considers ready for production. So once they have indicated that it is ready, it can be enabled on the website. This issue also also isn't really the best place to track the completion since its not where the localisation team has discussions.
