### ISSUE TITLE
Update ferris-says example on Getting Started page

### ISSUE THREAD

**Issue by ston1x** [rust-lang/www.rust-lang.org#1147]
### What needs to be fixed?

When reading the 'Getting started' page on https://www.rust-lang.org/learn/get-started the `ferris-says` version is outdated. On the page the version used is `'0.1'`, although there's a newer `'0.2.0'` version.

### Page(s) Affected

**Getting started**: https://www.rust-lang.org/learn/get-started

### Suggested Improvement

In order to keep the documentation up-to-date, I suggest using the newer version of `ferris-says`.

### Additional
https://github.com/mgattozzi/ferris-says/pull/14 here are the v`2.0.0` changes. It seems to be worth using this version at least because of the multibyte characters support.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However to be honest I would rather replace the getting started example with something that doesn't rely on third party libraries. If anyone has good starter example programs that only use `std`, feel free to post them in this thread and we can discuss them.

**Comment by Manishearth** [comment]
It's not quite third party, ferris-says was created as part of rustbridge and is often used in that context.

**Comment by XAMPPRocky** [comment]
I should have been clearer, I meant third party as in not shipped with the compiler, not as in its affiliation to the project.

Ideally I’d like for opening examples to not require any additional dependencies and for all examples on the website to be runnable in playground which the current examples aren’t.

**Comment by Manishearth** [comment]
I believe the _point_ of that example is to introduce people to the fact that it's super easy to pull in dependencies. A common issue for learners is that they don't realize this for a while and expect dependencies to be tricky and annoying.

**Comment by Manishearth** [comment]
We can get the playground to include ferris_says. The playground ships with popular crates.

**Comment by XAMPPRocky** [comment]
Sure though in that context I'm not sure how useful `ferris_says` is as an example of a dependency since it's an alternative `println!`, which you aren't going to use in a real world project. I think using something like `rand` would provide a more useful example and introduce people to a popular crate. Anecdotally in the workshops I've been in and mentored people were most often asking how to generate a random values, since it's something that is commonly included in other programming languages but is a third party library in Rust.

**Comment by ston1x** [comment]
Woah, didn't know `rand` is a different library. I think, however, that the intention of using the `ferris_says` crate is in telling about the mascot. There's also a 'Who’s this crab, Ferris?' heading below.

**Comment by Manishearth** [comment]
@XAMPPRocky Right, it's a _first_ example, baby steps, it's intentionally introducing an alternate hello world (given that cargo new already gives you the basic one for free), and nothing fancy. In an actual workshop you want to move away from that once folks are comfortable.

IIRC ferris-says as a first example was also developed from experience in workshops, I _think_ as a part of rustbridge.

Also, yes, @ston1x is correct.

**Comment by XAMPPRocky** [comment]
I feel like this is getting away from the point. Rust is a language that beginners often struggle with, if we look at last year's survey results better documentation is number one cited thing that needs improvement in Rust. So saying that our current getting started page is not sufficient shouldn't be controversial statement. A lot has changed in the two years since this example was written.

**Comment by Manishearth** [comment]
Documentation needing improvement does not imply that _this_ documentation needs improvement.

This example was written with experience from workshops, with a lot of thought put into it. I would undo that on a whim, the old example _was_ a simpler hello world.

**Comment by AliSajid** [comment]
This has been checked and merged. The team please close this.
