### ISSUE TITLE
A hyperlink mistake in simplified Chinese page

### ISSUE THREAD

**Issue by HHR2020** [rust-lang/www.rust-lang.org#1441]
### What needs to be fixed?
The "閱讀非官方翻譯！"("Read non-official translation" in English) hyperlink under the "阅读本书！" ("Read the book" in English )button should be replaced with a simplified Chinese one instead of the traditional Chinese one.

### Page(s) Affected
https://www.rust-lang.org/zh-CN/learn

### Suggested Improvement
Replace the hyperlink with "阅读非官方翻译！" https://kaisery.github.io/trpl-zh-cn/

**Comment by Manishearth** [comment]
谢谢你！

There's a fallback set up so that missing zh-CN keys automatically fall through to zh-TW, which is what happened here. I fixed it in https://github.com/rust-lang/www.rust-lang.org/commit/674b8bd6178c9ab9a8432db5579c9ef9a911d8ed , this will be on https://staging.rust-lang.org shortly, and we do occasional deploys.
