### ISSUE TITLE
Is there a link to Cargo on the website? How do I find 3rd party rust libraries?

### ISSUE THREAD

**Issue by timthelion** [rust-lang/www.rust-lang.org#1604]
### Motivation
I'm new to rust. I can't find a link to cargo on the website. How do I search for 3rd party libs?

**Comment by AliSajid** [comment]
Rust Team, This is a good idea. It seems unclear where the link would be at the current status of the website but having it there, in addition to having the links in the The Rust Book would make it easier for new people.

**Comment by senekor** [comment]
I don't see the added value because:

- We don't need to tell people that 3rd party libraries exist, that's a given.
- Search engine does the trick.

Even if we did add a link to crates.io. Its search feature is arguably not the best. When looking for a good library to use, the best approach is to use a search engine and reading forum dicussions about which libraries are well maintained at the moment and so on. I don't think the website can add much value to the process of finding libraries.

I don't think the website's purpose is to be a comprehensive index of everything that exists in the ecosystem.

**Comment by AliSajid** [comment]
I appreciate the response. I do have a few reservations that I'm adding inline below. If they are not convincing or they cause unnecessary work I would take my suggestions back.

>     * We don't need to tell people that 3rd party libraries exist, that's a given.

I agree with that. However, having a link to something that is ostensibly the official repository would be a good idea. Rust has excellent outreach and more and more people that are completely new to programming in general are gravitating towards it.

>     * Search engine does the trick.

While technically true, this is a slippery slope because one could argue the same about the rust book and other documentation.

> I don't think the website's purpose is to be a comprehensive index of everything that exists in the ecosystem.

Agreed.


As a counter example, Ruby and Python both link to their libaries. While Ruby does this with [a single page explaining what a ruby gem is](https://www.ruby-lang.org/en/libraries/), Python has a simple link to PyPI at the top of the page. They also have a showcase of what python libraries are able to do on the front page as well. Given maintainability concerns, I suggest using the Ruby model, if at all.

**Comment by timthelion** [comment]
"We don't need to tell people that 3rd party libraries exist, that's a given." - No it is not. Like seriously, rust is supposed to replace C. C does not have a centralized 3rd party library repository.

"Search engine does the trick." 

![image](https://github.com/rust-lang/www.rust-lang.org/assets/1391608/40a642cb-9646-423e-8599-c5a46d4ca398)

It is entirely unclear to a beginner that crates.io is an official website (is it?).

**Comment by Manishearth** [comment]
It's linked in multiple places; in the getting started tutorial and the cargo book, linked from the website.

I agree this could be improved. This issue seems primarily filed as a question, I'm closing it as such.

It's unlikely that major content changes will be done right now since the website is in maintenance mode and coordinating translations takes time. If the new council can come up with a permanent governance model for the website that would be nice; it is on my plate at some point to bring it up with them and lay out the challenges.
