### ISSUE TITLE
grammar.html is probably a stale website file

### ISSUE THREAD

**Issue by jorisgeer** [rust-lang/www.rust-lang.org#1621]
### What needs to be fixed?

The page 'doc.rust-lang.com/grammar.html' mentions : "The Rust grammar may now be found in the reference.", and mentions the grammar working group. This file seems appears orphaned and the style does not match the rest of the site. I am not sure if the text still applies.

I landed here by following a link from tree-sitter/tree-sitter-rust repo readme, 'The Rust Grammar Reference'.

### Page(s) Affected

grammar.txt

### Suggested Improvement

The Copyright in the footer shows 2011. This hints to the page probably being forgotten about.
The page needs to be either updated or removed.

**Comment by AliSajid** [comment]
I'll fix this but I don't see this page in the repo.

There is an entire section of the website at https://doc.rust-lang.org/beta/ that I cannot find in the repo. Please guide and I will fix it.

**Comment by AliSajid** [comment]
Bumping it up the list for review/guidance.

**Comment by senekor** [comment]
`doc.rust-lang.com/grammar.html` is a broken link, this is the right one:

https://doc.rust-lang.org/grammar.html

This content does not exist in this repository, so I recommend closing the issue. Since the page is clearly outdated, I don't think it matters much where the content comes from. (though I am curious)

If the original author still considers this a pressing concern, I recommend opending an issue on the treesitter-rust repo to update the outdated link.

**Comment by senekor** [comment]
[Found it](https://github.dev/rust-lang/rust/) in the rust repo. This is the general documentation shipped with every toolchain. You can generate / view it locally with

```
rustup doc
```

**Comment by Manishearth** [comment]
This issue does not pertain to this repo.
