### ISSUE TITLE
BBEdit not listed on the "Tools" page

### ISSUE THREAD

**Issue by siegel** [rust-lang/www.rust-lang.org#1625]
### What needs to be fixed?

The [Editors](https://www.rust-lang.org/tools) page does not list BBEdit as a supporting editor. BBEdit 14 shipped with built-in syntax coloring and function navigation support for Rust, and is preconfigured to use `rls` (but `rust-analyzer` works fine too).

### Page(s) Affected

https://www.rust-lang.org/tools

### Suggested Improvement

Add BBEdit to the list: https://www.barebones.com/products/bbedit/

**Comment by AliSajid** [comment]
Rust team, looking for advisory on whether this should be added. If yes I'd add a pull request

**Comment by senekor** [comment]
The goal of the tools page is not to provide an exhaustive list of editors with Rust support, as that would be an unreasonably long list at this point.

**Comment by danielpunkass** [comment]
@senekor I can understand why you wouldn't want to take on both the labor and the clutter of providing an "exhaustive list" of editors, but I wonder if you're overlooking the stature of BBEdit? It's one of the longest continuously developed apps for the Mac, and has been world renowned for decades as a top programming editor on the Mac. I just asked ChatGPT to list "the 5 most popular text editors for the Mac" and, granted ChatGPT is far from definitive, but it listed VS Code, Sublime Text, Atom, BBEdit, and TextMate. Just to say, you don't get in ChatGPT's list of "5 most popular" by accident.

Since the page highlights tools with "First-class editor support" and includes a number of well-known apps, it hardly seems that the goal has been to provide an exhaustive list, and I don't think that's what @siegel is asking for. He's asking for BBEdit, one of the most famous editors that happens to have first-class Rust support, to be included.

I think it would be a service to your audience to included BBEdit. Not to mention, it would balance the currently lobsided matrix of 7 apps.

**Comment by senekor** [comment]
Hi @danielpunkass, you are absolutely right. I had never heard of BBEdit before and promptly dismissed it as obscure, based on its unassuming website. I still don't think it should be included, but I do owe you some reasoning.

I would like to give it minus-points for being proprietary, paid and not cross-platform. But there are already other examples of that on the list. I also can't test the actual editor experience, since I don't in fact use a Mac.

Descisions like these are somewhat arbitrary, so the general policy right now is to not modify any content like that on the website at all. At least until the governance of the content is clarified by the leadership council.

I do want to make an exception though for that 8th spot in the grid. And there's a clear, default choice: The helix editor is much more popular among Rust devs than BBEdit, according to the [Rust Survey 2023](https://blog.rust-lang.org/2024/02/19/2023-Rust-Annual-Survey-2023-results.html#rust-usage). Helix is used by 8.9% of Rust devs, whereas BBEdit is just a small speck on the ["other" word cloud](https://blog.rust-lang.org/images/2024-02-rust-survey-2023/what-ide-do-you-use-wordcloud.png). The [PR to add helix](https://github.com/rust-lang/www.rust-lang.org/pull/1697) is pending.

**Comment by danielpunkass** [comment]
@senekor Thank you for reconsidering and explaining your decision.

**Comment by senekor** [comment]
@siegel I'm just noticing this now, your GitHub profile says you are affiliated with Bare Bones. This is genuinely just friendly advice, it's a good idea to be more forthcoming about that when promoting the product. I am strongly reminded of the [CodeCrafters drama](https://github.com/rust-lang/rustlings/pull/1760). It started very similarly, a harmless PR without an explicit declaration of affiliation. I'm not saying it's the same situation, just be aware that FOSS communities can be sensitive in this regard.
