### ISSUE TITLE
Kebab-case doesn't follow convention

### ISSUE THREAD

**Issue by MarkDBlackwell** [rust-lang/www.rust-lang.org#1651]
### Page(s) Affected

[Getting started](https://www.rust-lang.org/learn/get-started)

### What needs to be fixed?

Section "Generating a new project" tells users just getting started with Rust to type `cargo new hello-rust` to make their first project, which uses kebab-case.

_The Rust Programming Language_'s [Hello world](https://doc.rust-lang.org/book/ch01-02-hello-world.html) page says, "If you’re using more than one word in your filename, use an underscore to separate them." In other words, it tells users to follow [RFC 430](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md).

Regardless of the discussion in [Naming convention for crates #29](https://github.com/rust-lang/api-guidelines/discussions/29), section "Generating a new project" should conform to RFC 430.

The fact that _The Rust Programming Language_ and the Getting Started page differ regarding this convention is disconcerting and time-wasting for new users—at least it was, for this new user!

### Suggested Improvement

In section "Generating a new project," the command should be `cargo new hello_rust`. Thus snake_case should be used in the name of the new project. And *mutatis mutandis* for the rest of the section.

**Comment by Manishearth** [comment]
The book's documentation there is talking about _file names_, not _crate names_,  kebab-case crate names have been de facto idiomatic for quite a while (the dash translates to an underscore in source). Crate names are not Rust syntax and thus do not conform to that RFC.

**Comment by MarkDBlackwell** [comment]
Nevertheless, _The Rust Programming Language_ and the Getting Started page currently differ on how to spell multi-word names when giving them to `cargo new`. And why is this difference desirable?

Again, this difference is disconcerting to new users. (I'm providing a single data point for you to consider.) Please consider that I'm offering you valuable information! After all, how easy is it to collect initial impressions from new users? Not so easy. :)

Would it personally cost you much to align the Getting Started page with _The Rust Programming Language_? It seems I've stepped into a religious war. I'll proceed bravely, anyway. :)

I don't actually expect experienced Rust developers to understand the perceptions of new users easily. Naturally, I expect them to suffer the "curse of knowledge." :)

To me, it's no big deal! :) I'm happy to drop the issue, and hereby do so. :)

I'm just trying to help Rust—in a small way—boost its user acquisition. :)

BTW, to get all logical with you, when `cargo new hello-rust` creates the first directory, that directory's filename is `hello-rust`. Obviously, in Unix-like systems, directories are files, so directory names are themselves filenames. Why are you sure that _The Rust Programming Language_ excludes directories when it advises us how to spell multi-word filenames?

**Comment by Manishearth** [comment]
Okay, to start off, I was talking about the differences between the two pages _you linked_: one was dealing with rust modules and one was dealing with cargo crates. As I said, they have different norms. 

Now, you are right that the book [does](https://doc.rust-lang.org/book/ch01-03-hello-cargo.html) _also_ use underscores when talking about Cargo. I wasn't aware of that, that is perhaps worth fixing.

I understand that this is confusing! This is an extremely well known confusion point for newcomers, please disabuse yourself of the notion that you are introducing a hitherto unknown perspective here. Honestly I don't think the difference between the website and the book is the actual problem, because if they were uniform you'd eventually hit a similar issue when using real-world crates that use dashes.

This is the issue tracker for the website. As such we try not to change it too much. I'd recommend filing an issue on the repository for the book to see what they think needs to be done here. Personally, I'd argue for the book to also use dashes so that it gets an opportunity to teach the dash-to-underscore thing. But perhaps it's already been discussed, the book has had far more work put into this.

> BTW, to get all logical with you, when `cargo new hello-rust` creates the first directory, that directory's filename is `hello-rust`. Obviously, in Unix-like systems, directories are files, so directory names are themselves filenames.

I'm sorry, I'm a volunteer maintaining this website and I have very little time to give to pedantry and well-actuallying.

**Comment by MarkDBlackwell** [comment]
Upon further reflection, I now believe section "Generating a new project" is quite correct when it uses kebab-case in the command `cargo new hello-rust`.

Cargo then generates a new directory called `hello-rust`. And kebab-case is the convention for directory names on Unix.

Generally, therefore, kebab-case should be used in the (directory) names of new projects when using the `cargo new` command. And the book should align with the website and follow this convention (although it doesn't, yet).
