### ISSUE TITLE
Ubuntu 22.04.1 LTS pre-installed snap version of 'curl' breaks installer

### ISSUE THREAD

**Issue by BeepBo0p** [rust-lang/www.rust-lang.org#1711]
### What needs to be fixed?

When installing rust for Ubuntu 22.04.1 the installer is broken by the fact that the pre-configured (snap) version of curl does... something incorrect. Other ways of installing exist, but they just lead you directly into more problems like issues with setting up VS Code for rust-development.

### Page(s) Affected

https://www.rust-lang.org/learn/get-started

### Suggested Improvement

Add a line to the page if Ubuntu is detected, and warn that using the snap version of curl might break the installation command, and using another installation method might result in unforeseen problems.

**Comment by senekor** [comment]
> the pre-configured (snap) version of curl

What does pre-configured mean?

I just tried this in a Ubuntu **24.04** VM. `sudo apt install curl` gives me the deb package as expected. Rust installation works fine. Are people going out of their way to install snap curl instead of deb curl? If so, why? Has something changed in 24.04 such that it's not an issue anymore?

**Comment by senekor** [comment]
feel free to ping me if this is still relevant!
