### ISSUE TITLE
Misleading statement about Rustlings on Learning page

### ISSUE THREAD

**Issue by denispeplin** [rust-lang/www.rust-lang.org#1770]
### What needs to be fixed?

On `Learning` page, `Get started with Rust` contains three sections, from left to right: `The Book`, `Rustlings` and `Rust by example`.

The Rustlings sections states that it's an alternative to The Book, which I believe is not true.

I fell for it two years ago, when I was on a tight time budget and wanted to learn the language fast. After going through a bunch of exercises, felt demotivated because Rustlings didn't give me enough understanding of the language for continuing learning. I abandoned the learning of Rust.

This year, I tried again, and learned Rust using The Book with Rustlings as a companion to do more exercises. This way, I was able to finish both The Book and Rustlings.

I feel that while Rustlings give a lot of links to various resources, including The Book, The book provides much more consistent content and much better overall understanding of the language. So while Rustlings are indeed very useful, they can't be an alternative to The Book.

I must add that my recent background is Ruby and Elixir, so for someone from C/C++ area this might be not an issue.

### Page(s) Affected

https://www.rust-lang.org/learn

#### The simplest fix

- in `Alternatively, Rustlings guides you through downloading and setting up the Rust toolchain, and teaches you the basics of reading and writing Rust syntax, on the command line. It's an alternative to Rust by Example that works with your own environment.` remove `Alternatively` from the beginning (which statement I believe is not true).

#### Optionally

It's also stated that Rustlings is an alternative to Rust by Example, which is also not exactly true. While Rustlings provide exercises to perform, Rust by Example just provide a bunch of code samples with explanation. While it's useful, it serves a different purpose than exercises.

The sentence ` It's an alternative to Rust by Example that works with your own environment` can be replaced with something else, for example `It's a great companion for The Book that can be used as an additional sources of exercises`.

**Comment by Manishearth** [comment]
People have definitely learned Rust with the primary material being Rustlings, so I don't think this is accurate. Note that I said "primary" material: Googling or looking at the Book or asking questions elsewhere whilst learning still works.

Rather, different people have different learning styles, and it seems like Rustlings is not compatible with yours. The same is true for the Book for others. It's important to us that we don't put a single learning style on a pedestal and instead offer choices so that people (who know themselves better than we do) can pick what they think is best. Sometimes that choice ends up being wrong, but it's better than us making that choice for them.
