### ISSUE TITLE
Support of OpenBSD/adJ

### ISSUE THREAD

**Issue by vtamara** [rust-lang/www.rust-lang.org#1836]
The page https://www.rust-lang.org/tools/install reports OpenBSD/adJ 7.2 as unsupported paltform:

![image](https://github.com/rust-lang/www.rust-lang.org/assets/701221/ac7e016c-8042-4692-b755-05c92631a152)

On adJ/OpenBSD 7.2 running 
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

responds with:
```
rustup: unrecognized OS type: OpenBSD

```

On the same platform it works:
```
% doas pkg_add rust
% rustc --version
rustc 1.63.0
```

Following instructions of <https://github.com/vtamara/rustup/blob/master/CONTRIBUTING.md> after forking:
```
% cargo test --features=test
error: failed to parse manifest at `/home/vtamara/comp/cosmos/rustup/Cargo.toml`

Caused by:
  feature `workspace-inheritance` is required

  The package requires the Cargo feature called `workspace-inheritance`, but that feature is not stabilized in this version of Cargo (1.63.0).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance for more information about the status of this feature.
```

**Comment by remlse** [comment]
What is your question? The version of rust that is packaged by OpenBSD seems to be several versions behind, so it cannot compile rustup.

If you would like OpenBSD to be supported by rustup, you should probably open an issue in that repository. (Assuming such an issue doesn't exist already.)

This is the repository of the website. Since you are indeed having trouble on OpenBSD, I'd say the information on the website is correct for now.

**Comment by remlse** [comment]
Here you go: https://github.com/rust-lang/rustup/issues/2168
