### ISSUE TITLE
i found a wrong chinese translate

### ISSUE THREAD

**Issue by cjx2328** [rust-lang/www.rust-lang.org#1845]
### What needs to be fixed?

in the page translate button ,zh-tw not translate for 正體中文 (zh-TW) its wrong .
I found the wrong "正體中文 (zh-TW)" button in the language button of the page. The correct one should be"繁體中文 (zh-TW)"
### Page(s) Affected
 all pages

### Suggested Improvement
It is suggested to modify the text, thank you !

**Comment by Manishearth** [comment]
正體 is what it is typically called in Taiwan, whereas 繁體 is what it is called on the mainland. That translation is in Taiwanese Mandarin with traditional Chinese (zh-TW).

**Comment by swirling-wind** [comment]
> 正體 is what it is typically called in Taiwan, whereas 繁體 is what it is called on the mainland. That translation is in Taiwanese Mandarin with traditional Chinese (zh-TW).

@Manishearth 
The term "正體中文" and "正體 (pronounced as "zhèng tǐ")" could be problematic as a translation for "Traditional Chinese" because:

1. The literal of "正體" implies it is the "standardized form" or "legitimate form" of Chinese characters, which is misleading and carries political connotations that are best avoided in neutral language discussions. In comparison, the term "Traditional Chinese" in English doesn't carry the "standardized form" implication at all.

2. It also disregards the fact that mainland China, Singapore, Malaysia, Japan, and other regions use different character forms from Taiwan. Their character forms are different from each other. However, all their forms are legitimate standard and "正體" in their own regions. For example, Hong Kong Traditional Chinese can also be viewed as "正體" in Hong Kong, although Hong Kong Traditional Chinese is different from Taiwan Traditional Chinese.

A more accurate and neutral translation would be "傳統中文"(pronounced as "chuán tǒng zhōng wén").  It is the literal translation of "Traditional Chinese". It's more acceptable for all regions. Using "傳統中文" acknowledges the historical aspect of these character forms without implying superiority or standardization. This neutral term promotes better understanding and communication across different regions and cultural backgrounds.
