### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by apiraino** [rust-lang/www.rust-lang.org#1921]
### What needs to be fixed?

I reached the page https://www.rust-lang.org/team.html and got a 422 error. Debug from Rocket running on localhost:
```
GET /team.html text/html:
   >> Matched: (category_en) GET /<category>
   >> Parameter guard `category: Category` is forwarding: "No category called <team.html>".
   >> Outcome: Forward(422 Unprocessable Entity)
   >> Matched: (index_locale) GET /<locale> [3]
   >> Parameter guard `locale: SupportedLocale` is forwarding: ().
   >> Outcome: Forward(422 Unprocessable Entity)
   >> No matching routes for GET /team.html text/html.
   >> No 422 catcher registered. Using Rocket default.
   >> Response succeeded.
```

I reached that page by opening this [sub-team link](https://rust-lang.github.io/rfcs/#before-creating-an-rfc).

### Page(s) Affected

https://www.rust-lang.org/team.html

### Suggested Improvement

Is the page supposed to be there? Was it moved?

Will have a look at that, opening an issue as a reminder

**Comment by Manishearth** [comment]
It's an old link. It should link to /governance instead.

**Comment by ehuss** [comment]
I believe there is a larger problem where all of the [redirects](https://github.com/rust-lang/www.rust-lang.org/blob/0b933a84955ad879f79d5a489bbf54b41244bad9/src/redirect.rs#L5-L27) have stopped working for the past few days (perhaps since the last deploy?). This has resulted in broken links in various places. @weihanglo speculated it was the update to Rocket 0.5.

cc https://github.com/rust-lang/cargo/pull/13408 and https://github.com/rust-lang/blog.rust-lang.org/issues/1246

**Comment by Manishearth** [comment]
Hm yeah! when I saw this I was like "I swear there was a redirect there" but I figured it was `/team` and not `/team.html`.

**Comment by senekor** [comment]
You're right, the rocket v0.5 update caused this. I have a fix inbound.
