### ISSUE TITLE
Complementary install link

### ISSUE THREAD

**Issue by Rudxain** [rust-lang/www.rust-lang.org#1926]
### Summary
[`/tools/install`](https://www.rust-lang.org/tools/install) should include a link to [`rust-lang.github.io/rustup/installation`](https://rust-lang.github.io/rustup/installation)

### Motivation
The link provides more info about the installation process, along with optional shell completions.

### Drawbacks
I don't see any. It's just complementary material.

### Rationale and alternatives
- Q: Why is this design the best in the space of possible designs?
- A: It's a 1st-party source of info.
---
- Q: What other designs have been considered and what is the rationale for not
  choosing them?
- A: We could repeat the info from there, but that would be prone to sync problems in future updates, and it adds "bloat" to a page that's meant to be simple.
---
- Q: What is the impact of not doing this?
- A: Users having to use search-engines to get essential info about environment setup.

### Maintenance
No need, since the link points to an existing page with up-to-date info.

### Unresolved Questions

?

**Comment by senekor** [comment]
Where would you put the link? I don't see a huge benefit to the information on that site, not enough to justify more clutter. There is a link at the bottom of `/tools/install` for more information, which goes to the [Rust Forge](https://forge.rust-lang.org/infra/other-installation-methods.html). There are links to rustup in there as well, so it is already reachable with a few hops.

The tab completions are nice though, I don't see that mentioned anywhere else.

**Comment by Rudxain** [comment]
> There are links to rustup in there as well

Good point! I guess something more specific would be better, such as [sh completions](https://rust-lang.github.io/rustup/installation/#enable-tab-completion-for-bash-fish-zsh-or-powershell) (that was the main reason I opened this issue)

**Comment by senekor** [comment]
I also now noticed this part of the install page:

> For more information see the [rustup documentation](https://rust-lang.github.io/rustup/).

This links to _one page before_ the one you're proposing to link to. I don't think it makes sense to link to every page & section of the rustup book.

I can think of more reasons not to do this:
- The translations of the page are stale at the moment, adding a "new sentence" would make them drift apart even more.
- The rustup completions are quite discoverable, just running `rustup` will give you a list of subcommands including `rustup completions`. Running that tells you exactly what to do to enable them.
- I haven't had the completions enabled until now and I never missed them. Though I'm usually keen on good completions, which is why I run fish. Cargo even has built-in shorthands like `r`, `t` and `b`.

All of these points are small, but in total I see one small reason to do this and a couple small reasons not to do it, so I lean towards not doing it.
