### ISSUE TITLE
lighthouse pass on everypage

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#289]
- [x] Landing
- [ ] What
- [ ] WASM
- [ ] CLI
- [ ] embedded
- [ ] networking
- [ ] policies
- [ ] coc
- [ ] security
- [ ] media guide
- [ ] licenses
- [ ] learn
- [ ] governance
- [ ] community
- [ ] tools
- [ ] get started
- [ ] install

**Comment by skade** [comment]
Scores are: Performance, Accessibility, Best Practices, SEO.

100 is good, 0 is bad.

Most accessibility issues are due to having one item with bad contrast on the page. Revisit on single page rebrushs.

Performance issues are due to Cache Policy :https://github.com/rust-lang/www.rust-lang.org/issues/319

- [x] Landing: 98, 93, 100, 91
- [x] What: 100, 100, 100, 91
- [x] WASM: 100, 93, 100, 91
- [x] CLI: 98, 93, 100, 100, unused CSS
- [x] embedded: 96, 94, 100, 91, accessibility issue is an external iFrame by vimeo
- [x] networking: 99, 93, 100, 100
- [x] policies: 100, 100, 100, 100
- [x] coc: 99,100,100,100
- [x] security: 98, 93, 100, 100, https://github.com/rust-lang/www.rust-lang.org/issues/758
- [x] media guide: 99, 100, 100, 100
- [x] licenses  99, 98, 100, 100, https://github.com/rust-lang/www.rust-lang.org/issues/757
- [x] learn 98, 93, 100, 100, https://github.com/rust-lang/www.rust-lang.org/issues/758
- [x] governance 100, 98, 100, 91, https://github.com/rust-lang/www.rust-lang.org/issues/758
    - [x] Team subpage: 100, 100, 100, 100
- [x] community: 100, 100, 100, 100, potential savings on mobile with slightly smaller images
- [x] tools: 100, 91, 100. 100, https://github.com/rust-lang/www.rust-lang.org/issues/757,  https://github.com/rust-lang/www.rust-lang.org/issues/758
- [x] get started: 100, 93, 93, 100: https://github.com/rust-lang/www.rust-lang.org/issues/758
- [x] install: 99, 93, 100, 91: https://github.com/rust-lang/www.rust-lang.org/issues/758

Some pages report slight bugs like unused CSS, but that should be fixed when we do a general pass.
