### ISSUE TITLE
Not setting cache headers for images

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/www.rust-lang.org#319]
<b>Edit, @chriskrycho, 2018-11-20:</b> Original title was 'Flicker of phrase "Rust Logo" on screen transfer'. Updated after investigation.

---

Which switching pages, we sometimes get the phrase "Rust Logo" where the top-left logo is.

Example:

![rust_logo](https://user-images.githubusercontent.com/547158/48727705-defadf00-ec97-11e8-9016-81e5a660db7b.gif)

**Comment by coder543** [comment]
Right now, nothing at all is declaring a caching policy, so all content has to be reloaded every time. The static assets (images, css, etc.) are also not hashed, which makes caching even harder. Instead of `skeleton.css`, I would normally expect to see `skeleton-6c1d4c04bb55a87b9cb81ffdbd683662.css` or whatever, with an unlimited cache duration.

As I mentioned over on #372, I'm surprised that this isn't just a bunch of pre-built static content generated by `hugo` (or some Rust equivalent, if necessary) that's dumped into an S3 bucket and fronted by Cloudflare, CloudFront, Netlify, or something, which would make all of this easier.

**Comment by skade** [comment]
Closed via #768
