### ISSUE TITLE
"Get Started" does not convey "install"

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/www.rust-lang.org#437]
# Content Bug Report

## Page(s) Affected

The home page.

## What needs to be fixed?

I've heard from a few people that "get started" sounds like "here's a tutorial", not "here's how you install Rust". In general, it's that "how to install" is not as clear, but this was a specific action item.

## Suggested Improvement

I am not 100% sure yet, but I'm thinking about it.

**Comment by steveklabnik** [comment]
All of that is extremely off-topic. Let's keep it directly about this issue, thanks!

**Comment by ashleygwilliams** [comment]
when i originally working on this i thought about 2 buttons? though iirc @aturon wanted to keep the CTAs simple, i.e. only one. very amenable to hearing people's thoughts on iterating on this as i agree with the sentiment!

**Comment by nicoburns** [comment]
I agree with the idea of two buttons. IMO there are three main things that people who come to the home page might want:

1. Install Rust
2. Documentation
3. Information on what Rust is, why they should be interested, etc.

I suggest we make 1 and 2 CTAs at the top of the page. And put the content for 3 further down the homepage so that it corresponds with the "scroll" action.

Mockup (please ignore other changes, I'm using dev tools to prototype so I can't easily undo the other stuff atm):

<img width="1438" alt="screenshot 2018-11-29 at 21 53 14" src="https://user-images.githubusercontent.com/1007307/49254566-6aefd200-f421-11e8-9ee6-b8c1c02ba083.png">

**Comment by kolloch** [comment]
I agree with this issue and the last proposal is a huge improvement. I was also hoping for some sample code, see #479.

**Comment by ashleygwilliams** [comment]
sample code is not in scope, but i am happy to consider the extra button to link to install (in addition to get started). @aturon what are your thoughts?

**Comment by aturon** [comment]
I think with the addition of "Install" to the nav bar, this is no longer needed. And in particular, it's best if we can direct people to the "Get Started" page that walks through first steps in a bit more detail.

**Comment by XAMPPRocky** [comment]
Install is now in the navbar, it could probably be better but it fixes this issue.
