### ISSUE TITLE
Awkward wording in Ferris description

### ISSUE THREAD

**Issue by Zaechus** [rust-lang/www.rust-lang.org#470]
The explanation of Ferris in the Get Started page seems literarily awkward to me and others I've shown it to.  The first section uses the word "which" three times in a row (this sounds awkward), for example, and that entire thought seems over explained and could be simplified to be more concise (this is a suggestion).  I'm also not sure of the reason for the inclusion of "(they/them)" in the first part (possibly unnecessary?).  The second explanation seems OK but could possibly be improved to be better worded.

**Comment by magnet** [comment]
Same thoughts.

**Comment by ashleygwilliams** [comment]
If you have an improvement to the wording, I would happily accept a PR or suggestions as comments in this issue! Thanks!

**Comment by magnet** [comment]
Simplified version (I guess people know crabs are crustaceans)

> Who’s this crab, Ferris?
> Ferris is the unofficial mascot of the Rust Community. Rust programmers call themselves "Rustaceans", a play on the word "crustacean".
> 
> Ferris is a name playing off of the adjective, "ferrous", meaning of or pertaining to iron. Since Rust often forms on iron, it seemed like a fun origin for our mascot’s name!

**Comment by ashleygwilliams** [comment]
i think maybe we can link to what a crustacean is? also i'd like to keep the pronouns (they/them) in there. its an important detail. if you want to make a PR with ur changes and my feedback i would happily accept that!

**Comment by Maxgy** [comment]
@ashleygwilliams I can make the PR in a bit.  Also, could you elaborate on the reason for including "(they/them)?

**Comment by ashleygwilliams** [comment]
i think it's nice to include because 1) people often assume that Ferris is a boy and use (he/him), but Ferris is non binary, 2) to quietly signal that pronouns are something the Rust community cares about and that this is a space that is welcoming to folks who have identities like that!

**Comment by magnet** [comment]
@ashleygwilliams As far as I know gender pronouns such as these are mostly used in America, which feels a bit weird on a website targeting an international audience. I am very happy the Rust community is welcoming to everyone, I just feel it is unnecessary to give a gender to a PL mascot. I've personally never assumed any specific gender for Duke. It's maybe a cultural thing, but we don't really attribute a gender to animals or cartoon characters from my part of the world. :)

**Comment by 8573** [comment]
I'd like to suggest that the language specifying the personal pronouns be more explicit, such as a sentence "We refer to Ferris with the pronouns "they", "them", etc., rather than with gendered pronouns." at the end of the section, because I easily can imagine someone who isn't already familiar with seeing personal pronouns specified like "Ferris (they/them)" having no idea what "they/them" in parentheses is intended to mean (maybe especially if they're less familiar with English).

**Comment by ashleygwilliams** [comment]
That’s an awesome suggestion @8573! I really love that ❤️

**Comment by FrostbittenKing** [comment]
> @ashleygwilliams As far as I know gender pronouns such as these are mostly used in America, which feels a bit weird on a website targeting an international audience. I am very happy the Rust community is welcoming to everyone, I just feel it is unnecessary to give a gender to a PL mascot. I've personally never assumed any specific gender for Duke. It's maybe a cultural thing, but we don't 

> @ashleygwilliams As far as I know gender pronouns such as these are mostly used in America, which feels a bit weird on a website targeting an international audience. I am very happy the Rust community is welcoming to everyone, I just feel it is unnecessary to give a gender to a PL mascot. I've personally never assumed any specific gender for Duke. It's maybe a cultural thing, but we don't really attribute a gender to animals or cartoon characters from my part of the world (that is, unless they explicitly do themselves like Mickey Mouse!) :)

Not to mention in serious topics like coding this gender identity politics bollocks has no place, in my opinion. If someone cares about that in software development, he/she/it should btfo. I don't need people that get emotional about that stuff. I don't care if they are male female, or trans (no i won't list gay here, because that is a sexual orientation and no gender identity - which is a complete different can of worms), I only care about their code quality (if it is good, she can assume whatever identity she wants) but when they care about being "included" with their pronouns, I _do_ care. Politics should stay out of code. They should write about these topics in their blog or the annoying buzzfeed op-ed, vox and what not, but.. freely adopted from George Carlin: "Keep thy religion to thyself.".
I rather like Linus Torvald's blunt personality. It keeps the code cleaner. A does something stupid, Linus fetches the jackhammer. Someone gets emotional - Linus fetches the jackhammer.

Tbh, I started the rust tutorial yesterday and instantly dropped it after reading this sentence.

**Comment by skade** [comment]
Note for everyone who ventures here: the reasons this issue is locked is because it irregularly receives insulting spam.

The reasons why Ferris gender/pronoun is mentioned on the page is plain and simple: people ask us that question, we answer the question. It's an information page after all.
