### ISSUE TITLE
2018 Announcement Location

### ISSUE THREAD

**Issue by mitsuhiko** [rust-lang/www.rust-lang.org#605]
# Design Feature Request
## Summary

Someone probably already mentioned it but as a EU citizen I'm already so used to stupid cookie banners coming up that I looked multiple times to dismiss the 2018 announcement on the top of the website. It looks too much like a thing I want to dismiss after having it seen once.

I understand why it's there, that it plays a role and nobody will make a dismiss button but I tried what happens if it gets moved down and it looks quite nice:

<img width="1192" alt="screenshot 2018-12-07 at 21 35 36" src="https://user-images.githubusercontent.com/7396/49671476-48d10200-fa68-11e8-84e5-7d3228c07738.png">

## Motivation
I think it looks less distracting.

**Comment by ashleygwilliams** [comment]
thanks for filing @mitsuhiko ! i think this looks better as well! currently this flash message is part of the layout template, but i think we could move it to just the index page- partially because i do believe if we put it on every page, the pages that start with a red panel may look a bit odd- if you are interested in making a PR i would happily accept it!

**Comment by mitsuhiko** [comment]
Added a PR
