### ISSUE TITLE
Explain what Rust actually is on the landing page

### ISSUE THREAD

**Issue by Ristarg** [rust-lang/www.rust-lang.org#612]
# Content Feature Request
## Summary
Explain what Rust is on the landing page -- a programming language.

## Motivation
On the landing page, a lot of time is spent praising Rust, yet at no point (if you don't count Chucklefish testimony) is it explained what Rust actually *is*. Without clearly communicating what Rust is, it's confusing and not useful to a person who might be first visiting the website without prior knowledge.

## Drawbacks
None that I can see. I have yet to visit a PL website that doesn't have "programming language" on the landing page.

**Comment by tshepang** [comment]
Is it a likely thing to end up on the page without knowing in advance you are visiting a site of a programming language?

**Comment by eddyp** [comment]
I don't think is relevant if it's likely or not. You should know this is a programming language, not some framework or some other thing.

**Comment by Maxgy** [comment]
Well, the title of the page is "Rust programming language" and the website url has "rust-lang" in it.

**Comment by bjadamson** [comment]
> Is it a likely thing to end up on the page without knowing in advance you are visiting a site of a programming language?

Yes. Think about non-power users landing here, because they are doing research for teammates.

A contrived example, think about the 12yr old kid who plays the Rust game, but accidentally lands on the rust programming language page. Maybe they would develop an interest in Rust, and thus programming,  because their favorite game has the same name.

**Comment by aidanhs** [comment]
Putting myself in the shoes of a non-technical person (often decisionmakers for using Rust) who may have heard about Rust from their team, I could see it taking little while for it to sink in that it's a programming language. I can sympathise with this suggestion.

**Comment by ashleygwilliams** [comment]
i also agree and advocated for maintaining the words "programming language". this is fundamentally something that @aturon has taken lead on so we should wait for his comment on how to proceed.

**Comment by sanxiyn** [comment]
Any update?

**Comment by yoshuawuyts** [comment]
@sanxiyn Sorry for the lack of updates!

Between Rust 2018, the holidays and the rust all-hands most people working on this have been a bit busy. There's been talk about forming a Rust Website team; hopefully there should be more bandwidth to explore copy changes once that ball gets rolling.

**Comment by sanxiyn** [comment]
Any update? Rust landing page still does not tell what Rust is.

**Comment by yoshuawuyts** [comment]
@sanxiyn getting the ball rolling again has been taking a bit longer than I'd hoped for. I don't have an ETA, but am confident we'll get there eventually (:

**Comment by skade** [comment]
A change would certainly be accepted, but the proposed change would lengthen the claim and take a lot of steam out of it. I would avoid to discuss changing the claim, instead finding another option to weave it in.

**Comment by eddyp** [comment]
@skade What if we replace "Rust" with "The Rust Programming Language"?

(btw, the same issue of order occurs in the Android app I'm using, so it's probably something in the meta data / API data)

**Comment by skade** [comment]
@eddyb I'm not very hype about that either. It's totally okay (and usual) to make the claim and intro without stating the exact nature of the product for brevity sake.

**Comment by JakeTherston** [comment]
> It's totally okay (and usual) to make the claim and intro without stating the exact nature of the product for brevity sake.

The issue here is that the page does not state the nature of the product at all. Not even generally.

I would urge you to give precedence to function over design. Internet users have (rightfully, imo) come to expect that landing pages contain some sort of description of the products or services being shown. The page, as it currently is, is simply not useful for the vast majority of people. The page showcases positive but secondary aspects of its subject while never delving into what that subject actually is. As it stands, people who aren't aware of Rust will have to leave the page and visit another source (e.g. Wikipedia) to fill in the missing information. Even from the perspective of web design, forcing people to click or tab away is the last thing you want a **landing page** to do.

I'll also be blunt, the current landing page completely fails to achieve its purpose. In fact, I believe it actively goes against it. I don't say this to attack you or anyone else who works on this project. I'm simply stating what I see (as a professional who does this for a living) to be an objective flaw.

Again, I urge you to rethink this through. Run a focus group (even a small informal one) even if you're absolutely certain the current design is acceptable. Discuss their experience to see how well the current design achieves its goals.

> Like, to be clear, I appreciate that people want to fix this, I don't believe simply expanding one of the current texts is the fix.

Since expanding preexisting texts is off the table, how about adding a new section that describes what rust is (titled "What's Rust?"?) before the section "Why Rust?"? 

Would such a change be reasonable?

**Comment by skade** [comment]
Sorry for taking the weekend to come back to you.

I circled the thing around a little with some designer friend and we ended up with the following: Change the claim to "A language empowering everyone in building reliable and efficient software.". This avoids extending the claim too long ("programming" is implied in "software").

Considering adding a section on top of the main content: we'd like to avoid that. The page is consciously laid out as putting the "what" over the "how". Because Rust has many diverse use-cases, we move code to the relevant sections. Embedded engineers should go the embedded site, network engineers to the network site, etc.

There's a suggestion here for making the overview better:
https://github.com/rust-lang/www.rust-lang.org/issues/351

Generally, if you want to link friends to the page, consider sending them to the landing page of their area of interest.

**Comment by eddyp** [comment]
@skade That sounds awesome.

May I ask if the change from "to build" into "in building" is intentional? Even if the later is also proper English, the former seems easier to parse for non native speakers. At least that's how people thought when asked.

**Comment by eddyp** [comment]
... and the former is shorter 😉

**Comment by skade** [comment]
@eddyb Thanks for checking that. It was intentional, but given that you collected more feedback than I had, I'll change it back :).

**Comment by skade** [comment]
Amended the PR.

**Comment by skade** [comment]
Done. Closing this in favor or #351 and #445, which should cover the "deeper look at Rust" aspect, once implemented.

**Comment by eddyp** [comment]
@skade thanks. BTW, stop pinging eddyb and ping me, eddyp instead 😉

**Comment by skade** [comment]
@eddyp right, damn suggestions. We also need an @eddy(d), and we got all the confusion :+1:
