### ISSUE TITLE
Colourscheme adjustment, footer

### ISSUE THREAD

**Issue by drahnr** [rust-lang/www.rust-lang.org#621]
# Design Feature Request
## Summary
Change the footer text colour to something different from light on black background.

## Motivation
Why are we doing this? What use cases does it support? What is the expected
outcome?

From my perception, the contrast is too high - combined with the small text this leads to hardly readable lines

## Drawbacks
It adds effort to find a different set of colour shades for foreground and background.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?
Not claiming to be the best, just trying to improve readabiility.
- What other designs have been considered and what is the rationale for not
  choosing them?
This is the least invasive minimal change I could think of.

- What is the impact of not doing this?
Fewer people will read the footer.

## Maintenance
How will this design be maintained? Who will do it?
The cost of maintenance will be no higher than the current. Please correct me if I am wrong.

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?
None as far as I can say, but again, I am happy to stand corrected.

**Comment by jacobpledger** [comment]
I think font size might help a bit. Larger characters at normal weights, or maybe even light. My first reaction is to suggest that you steer clear of heavy font-weights, because I think the "Get Help", "Terms and Policies" and "Social" headers might already be a bit thick, causing the characters to bleed together a little. After some thought though, I think you might be able to combat this with additional character spacing.
To follow the original suggestion, could a less deep black work? Something even _slightly_ more matte?
`#111111`?

**Comment by drahnr** [comment]
It seems my previous response got lost.

@jacobpledger the colour change would be my prefered option.

@ashleygwilliams if that is not desired then:

maybe adding a lighter shading around the text, either a slightly lighter black, or slightly darker yellow tone might help. A slight increase in font weight would also improve readability.

**Comment by travisboss** [comment]
I think instead of black as outer space will allow simply going with `background-color: hsl(0, 0%, 19%);` would move to a gray look which is not all bad.  I can make a PR on this if we all agree.

I have attached a screenshot.
![www rust-lang org_footer](https://user-images.githubusercontent.com/16948721/60193041-993d6080-97fc-11e9-9476-99e2c010170e.png)

**Comment by skade** [comment]
@travisboss This looks useful! Could you open that as a PR so that we can try it out?

**Comment by travisboss** [comment]
Sure!

**Comment by XAMPPRocky** [comment]
Closing as no longer relevant, as the footer's colour has changed.
