### ISSUE TITLE
Font size on the website is too big

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/www.rust-lang.org#641]
# Design Bug Report

## Page(s) Affected

All the pages on the website.

## What needs to be fixed?

In the current website, the `font-size` is set to `1.5em` in all the website, basically making all the text on the page 50% larger than on every other website.

This is what I see on my 1366x768 laptop at fullscreen:

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/2299951/49877932-c6a95a80-fe26-11e8-8223-bbfaf556b795.png">
</td>
<td>
<img src="https://user-images.githubusercontent.com/2299951/49877933-c6a95a80-fe26-11e8-8968-4943d93735ae.png">
</td>
</tr>
<tr>
<td>"Proper" font size (example: the blog)</td>
<td>The current website</td>
</tr>
</table>

Zooming out to 80% restores "proper" font sizes on the website.

## Suggested Improvement

Restore font size to `1rem` across the website.

**Comment by chriskrycho** [comment]
Note that we actually intentionally *increased* the text size throughout because of some of the issues raised in #412 and #525. The goal is to have reasonably good readability as a baseline while allowing users to control their experience of it with zoom as normal. Especially on blocks of text, the lower font size was a serious problem for readability for anyone who didn't have *great* vision.

Also note that the issue here is actually the `font-size` declaration on the `html` element; you can remove the `font-size: 1.5em` from `body` and it doesn't change the actual sizes at all (and should indeed be removed).

**Comment by pietroalbini** [comment]
> Especially on blocks of text, the lower font size was a serious problem for readability for anyone who didn't have great vision

Well, 1rem font size is the standard everywhere for text though, even here on GitHub. With 1.5rem font size though the amount of content you see on the page is really low, mostly because everything is huge.

**Comment by ashleygwilliams** [comment]
so this is a complicated issue. on one hand- we have received feedback that the density of the site is too low, others have asked for the font size to be alternately larger and smaller. we'll need to reconcile this feedback but at the moment i'm not sure we have the capacity for a larger overhaul.

because bumping the text size improved accessibility/legibility- i am inclined to keep that, as that seems more important than the lower information density, which can also be solved by reducing whitespace and changing layout. 

for the moment i am going to close this issue- there are a few other issues re information density #412  that i'd encourage you to move this conversation to!
