### ISSUE TITLE
Broken link on https://forge.rust-lang.org/other-installation-methods.html#source

### ISSUE THREAD

**Issue by markelog** [rust-lang/www.rust-lang.org#662]
# Content Bug Report
On the https://forge.rust-lang.org/other-installation-methods.html#source page there is phrase "Past releases can be found in the archives." "the archives" part is the link which leads to nowhere.

Also, before, you could have gotten list of all possible rust installations through the https://static.rust-lang.org/dist/index.txt resource, but now it's no longer available :/. Is it possible to bring it back?

## Page(s) Affected
https://forge.rust-lang.org/other-installation-methods.html#source

## What needs to be fixed?
The link

**Comment by pietroalbini** [comment]
The list has been removed a few months ago because it was taking like half an hour to generate every time we pushed artifacts (on a nightly/beta/stable release). Bringing it back is going to have the same problems (aka being rate limited *a lot* by AWS to fetch all the files in that bucket).

cc @alexcrichton

**Comment by markelog** [comment]
According to my notes that happended 8 days ago, hm.

Do you think there would be any way to see history of previous version of the language?

For example in other languages - 

1. elm - https://dl.bintray.com/elmlang/elm-platform
1. go - https://golang.org/dl/ "Archived versions"
1. nodejs - https://nodejs.org/dist/
1. python - https://hg.python.org/cpython/tags
1. ruby - https://cache.ruby-lang.org/pub/ruby/

It seems such info doesn't have to be as verbose as it was :)

**Comment by pietroalbini** [comment]
Those pages only include the proper releases, and that should be easy to generate from the git tags (https://github.com/rust-lang/rust/releases). https://static.rust-lang.org/dist/index.txt also contained all the previously released nightlies and betas.

**Comment by tones111** [comment]
Where can one go to download previous binary releases?  For example, now that 1.33 is out, where can the windows / linux pre-built installers for 1.32?

**Comment by skade** [comment]
@pietroalbini Does that mean hitting the github API on every build of the page? Can we run into limits there?

**Comment by pietroalbini** [comment]
So, there are two problems related to this issue.

### Users want to download (even old) Rust versions from the website

If someone wants to download Rust without going through rustup at the moment is redirected by the website to [this forge page](https://forge.rust-lang.org/other-installation-methods.html). There are a few issues with that:

* The forge page only links to the current release's artifact, without any way to downloading past releases without manually fiddling with the URL.
* The forge is a rather unfriendly website to redirect people to: the design is basically "programmer art" and it's meant for contributor docs anyway.

What I think we should do to fix this problem is to move that forge page to the website, redesign it in a better way and include past releaes as well. @kennytm already wrote the code on the forge to [fetch all the download links from an arbitrary channel/version](https://github.com/rust-lang/rust-forge/blob/master/src/main.rs) so we just need to move that code to the website and add some nice design on top of it.

If we also want to get past versions the easiest way is to [fetch the list of tags from the GitHub API](https://developer.github.com/v3/repos/#list-tags) (with proper pagination). Rate limiting shouldn't be a problem if we use an auth token and we cache the result for 2 minutes (all the caching code is already in place on the website).

### Automated tooling wants to get a list of all the files on static.rlo

This means the restore of the index page on the static.rust-lang.org website, and it's already tracked on https://github.com/rust-lang/rust-forge/issues/215, with a possible solution infra-wise in sight. To be clear I'm **strongly** opposed to link that page anywhere near a place end-users could see it: it's huge (that archived version Yoshua linked is ~10mb with 31k links in it, and it will constantly grow) and not practical at all if you want to find where to download a release.

**Comment by infinity0** [comment]
The index page could be split up by type-of-artifact in order to make it smaller. In Debian we're usually only interested in the source code, and much less often the binaries.

**Comment by pietroalbini** [comment]
For the Debian use case https://github.com/rust-lang/rust-forge/issues/215#issuecomment-488877976 is probably the best thing from both projects' point of view. We just need to find the time to implement it infra-wise.

**Comment by andrewchambers** [comment]
Could someone tell me where to find a source tarball? The forge website doesn't have an index or a working link to a release tarball. This is basic and critical infrastructure.

**Comment by XAMPPRocky** [comment]
I'm closing this as the original issue has been is no longer relevant, and seems like the rest of this issue belongs on the rust forge repo.
