### ISSUE TITLE
Comma is awkwardly on the next line

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#711]
# Content Bug Report

## Page(s) Affected
![screenshot_2019-02-18 install - rust programming language](https://user-images.githubusercontent.com/679122/52973600-390a5e00-33c7-11e9-896b-3fbad6016cb9.png)

## What needs to be fixed?
The lone comma under “Toolchain management”.

**Comment by chriskrycho** [comment]
Nice find! The problem is that [this link](https://github.com/rust-lang/www.rust-lang.org/blob/a54cde653b77ca4f63d3f3967631698e76f24286/templates/tools/install.hbs#L39-L41) wraps across multiple lines and inserts white space between the end of the preceding line. An easy fix would simply be to put the `</a>,` immediately after the word "platforms" instead of wrapping it into the next line.

**Comment by nagisa** [comment]
The problem is also relevant to the link just before the one with the comma (notice that whitespace has the underline under it)
