### ISSUE TITLE
User (Friends of Rust) page should have link to job page

### ISSUE THREAD

**Issue by toidiu** [rust-lang/www.rust-lang.org#734]
# Content Feature Request
## Summary
The "Users of Rust" page should also have a link or email to apply for Rust jobs.

Relevant links:
https://www.rust-lang.org/production/users
https://github.com/rust-lang/www.rust-lang.org/blob/master/src/data/users.yml

## Motivation
Make recruiting/applying for Rust positions seamless. This page already compiles the companies using Rust it would be nice to surface the preferred way to connect with these companies.

## Drawbacks
Adding contact links could lead to spam.

## Rationale and alternatives
The contact links could be optional. 

## Maintenance
It should be in the interest of the company to surface these links since hiring is generally a difficult problem for most companies.

An initial effort would have to be made to update the data.

**Comment by yoshuawuyts** [comment]
@toidiu I like your idea -- this seems like something that's not too hard to add, and would probably benefit folks!

There's the question of consent though: I believe these companies have been reached out to before being included on the site, and linking to their hiring pages might not have been part of that conversation. We should probably be careful not to overstep our bounds here.

cc/ @carols10cents @aidanhs I feel both of you might have more insights on this topic. I think your perspectives here would be valuable.

**Comment by steveklabnik** [comment]
I think that this is going to be too hard to keep current.

**Comment by toidiu** [comment]
I personally think that enabling crowdsourcing is the way forward here. This largely means adding a link to the github data page with some instructions. And if not then it not something of value and no one need maintain it.

The entire assumption is that finding a Rust developer is difficult for a company and for a developer its not obvious which companies are actually using Rust in production. (there should also be a complementary site called 'Freelances of Rust' but thats another topic).

adding info:
- the effort should largely be company driven (assuming that hiring interested developers is a large enough incentive)
- initially an email link(career@company.com) is probably the easiest and most useful. a link to a career page can contain non rust relevant topics.

removing info:
- a link to the github page so users can make pr's to update/remove dead emails.

**Comment by skade** [comment]
The friends/users page is not intended as a hiring board. The current page is intended to reduce any kind of volatile information with high churn. This goes as far as:

* Not having a conference page that needs constant updating
* Avoiding linking to external resources that have not shown multi-year track-record

It's a serious problem to find contributors for frequent content-checking and we can't rely on companies or other external partners to keep the data up-to-date.

Also, historically, we used to run a job board on an external service and it hasn't worked out.

Crowdsourcing still keeps us responsible for quality control.

Finally, we don't endorse service companies and freelancers on the website, as that would make use responsible for checking their quality - which would open the whole can of worms that those requirements will be exclusive or the quality of the lists cannot be relied on. What happens if we need to kick people out?

**Comment by toidiu** [comment]
@skade your comments make a lot of sense.
