### ISSUE TITLE
Redirect doc.rust-lang.org to /learn

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#761]
# Content Feature Request
## Summary
Followup of:
https://github.com/rust-lang/www.rust-lang.org/issues/696

Now that we have /learn, we don't need doc.rust-lang.org to be the main page of the rust offline documentation. The latter should still be maintained.

## Task

* [x] Setup a redirect from https://doc.rust-lang.org to https://rust-lang.org/learn

## Motivation
Consistency. The learn page will be translated.

**Comment by pietroalbini** [comment]
Implemented the change on https://dev-doc.rust-lang.org. Can someone from @rust-lang/docs check that everything is correct and acknowledge the change? Some notes:

* The redirect is only done for the root. Release or channel specific indexes like https://dev-doc.rust-lang.org/1.34.1/ are not redirected.
* The redirect is a temporary redirect (302) instead of a permanent redirect (301). This prevents breaking things if we want to change the redirect target in the future.
* The `dev-doc` environment is a bit strange and it contains mostly just stable releases. No beta is present and the latest nightly is 1.19. :sweat_smile:

**Comment by pietroalbini** [comment]
Instructions for other infra team members to apply the change on doc.rlo if I don't get around to it:

* Deploy version 9 of the `docRustLangOrgRouter` lambda to the CloudFront distribution
* Invalidate the cache for `/*`

**Comment by steveklabnik** [comment]
Looks good to me!

**Comment by pietroalbini** [comment]
Changes are deployed!
