### ISSUE TITLE
Code example overflow on Networking page

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/www.rust-lang.org#926]
# Design Bug Report

## Page(s) Affected
[Networking](https://www.rust-lang.org/what/networking)

## What needs to be fixed?
Code examples in Get Started section of the Networking page

## Suggested Improvement
Make it so that the code wraps instead of overflowing the page.

Desktop:
![image](https://user-images.githubusercontent.com/54848917/66011651-feef5780-e491-11e9-9807-092969b2df13.png)
Mobile:
![image](https://user-images.githubusercontent.com/19353212/66011902-e469ae00-e492-11e9-8477-3374918a4383.png)

EDIT: After further investigation, this problem seems to affect multiple pages.

**Comment by simonxabris** [comment]
Hey

Came across this issue and tried to fix it and after a couple tries managed to get it to look like this:
<img width="1440" alt="Képernyőfotó 2019-10-02 - 21 08 25" src="https://user-images.githubusercontent.com/27497229/66074384-658b7880-e559-11e9-8904-f886786aa211.png">

Instead of what it looks like on the live site. The problem is that you have a `white-space: no-wrap` rule on the `<code>` tags, but if you remove that it will look like this:
<img width="1440" alt="Képernyőfotó 2019-10-02 - 21 14 48" src="https://user-images.githubusercontent.com/27497229/66074615-e3e81a80-e559-11e9-8080-d19cb25fd90c.png">

So I ditched the code tag and put it in a div and styled that. I'd be happy to submit a pr if you are interested!

**Comment by greggman** [comment]
This isn't just the networking page. I'm guessing it's all pages. I thought I'd try to learn rust today only to find that the examples are unreadable

<img width="1045" alt="Screen Shot 2019-10-08 at 19 17 08" src="https://user-images.githubusercontent.com/234804/66388142-77a96300-ea00-11e9-8d40-43bb40434745.png">

**Comment by JohnTitor** [comment]
This is fixed on the latest deployment, can be closed.

**Comment by Maxgy** [comment]
This bug appears to be fixed. Closing.
